// Username editor shown in Settings. Players get an auto-generated name on
// first sign-in (e.g. Trainer_04217). Choosing a custom name for the first
// time grants a small in-game reward (gold + Town Portal Scroll) once per
// account, tracked server-side via the auto_generated flag.

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { User as UserIcon, Pencil, Check, X, Gift } from 'lucide-react';
import { useMyUsername, setMyUsername, validateUsername } from '@/hooks/useUsername';
import { toast } from 'sonner';
import { useGame } from './state';

const FIRST_NAME_REWARD_GOLD = 500;

export function UsernameEditor() {
  const { username, autoGenerated, loading, refresh, isAuthenticated } = useMyUsername();
  const { dispatch } = useGame();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState('');
  const [saving, setSaving] = useState(false);
  const [localError, setLocalError] = useState<string | null>(null);

  if (loading) {
    return (
      <div className="space-y-2 pt-4 border-t">
        <Label className="text-base flex items-center gap-2">
          <UserIcon className="w-4 h-4 text-primary" />
          Public Username
        </Label>
        <p className="text-xs text-muted-foreground">Loading…</p>
      </div>
    );
  }

  if (!isAuthenticated) {
    return (
      <div className="space-y-2 pt-4 border-t">
        <Label className="text-base flex items-center gap-2">
          <UserIcon className="w-4 h-4 text-primary" />
          Public Username
        </Label>
        <p className="text-xs text-muted-foreground">
          Sign in to claim a public username and post to tower leaderboards.
        </p>
      </div>
    );
  }

  const startEdit = () => {
    setDraft(username ?? '');
    setLocalError(null);
    setEditing(true);
  };

  const cancelEdit = () => {
    setEditing(false);
    setDraft('');
    setLocalError(null);
  };

  const save = async () => {
    const err = validateUsername(draft);
    if (err) {
      setLocalError(err);
      return;
    }
    setSaving(true);
    const result = await setMyUsername(draft);
    setSaving(false);
    if (result.ok === false) {
      setLocalError(result.error);
      return;
    }
    if (result.wasFirstManual) {
      // One-time reward for personalising the auto-generated name.
      dispatch({ type: 'ADD_TOWN_GOLD', amount: FIRST_NAME_REWARD_GOLD });
      dispatch({
        type: 'STORE_ITEM',
        item: {
          id: 'town_portal_scroll',
          name: 'Town Portal Scroll',
          quantity: 1,
          type: 'potion',
          effect: 'town_portal',
          value: 0,
        },
      });
      toast.success(`Username set to ${result.username}`, {
        description: `Reward: +${FIRST_NAME_REWARD_GOLD} gold and 1 Town Portal Scroll`,
        icon: <Gift className="w-4 h-4" />,
      });
    } else {
      toast.success(`Username set to ${result.username}`);
    }
    setEditing(false);
    setDraft('');
    setLocalError(null);
    refresh();
  };

  return (
    <div className="space-y-2 pt-4 border-t">
      <Label className="text-base flex items-center gap-2">
        <UserIcon className="w-4 h-4 text-primary" />
        Public Username
      </Label>
      <p className="text-xs text-muted-foreground -mt-1">
        Shown on tower leaderboards. 3–20 characters: letters, numbers, _ or -.
      </p>

      {autoGenerated && !editing && (
        <div className="rounded-md border border-primary/40 bg-primary/5 px-3 py-2 text-xs flex items-start gap-2">
          <Gift className="w-4 h-4 text-primary mt-0.5 shrink-0" />
          <span>
            We picked this name for you. Choose your own to claim{' '}
            <strong>+{FIRST_NAME_REWARD_GOLD} gold and a Town Portal Scroll</strong>.
          </span>
        </div>
      )}

      {!editing ? (
        <div className="flex items-center gap-2">
          <div className="flex-1 rounded-md border bg-muted/40 px-3 py-2 text-sm font-mono">
            {username ?? <span className="text-muted-foreground italic">Not set</span>}
          </div>
          <Button variant="outline" size="sm" onClick={startEdit}>
            <Pencil className="w-3.5 h-3.5 mr-1" />
            {username ? 'Edit' : 'Set'}
          </Button>
        </div>
      ) : (
        <div className="space-y-2">
          <Input
            value={draft}
            onChange={(e) => {
              setDraft(e.target.value);
              if (localError) setLocalError(null);
            }}
            placeholder="e.g. SlimeKing_42"
            maxLength={20}
            autoFocus
            disabled={saving}
            className="h-9 text-sm font-mono"
          />
          {localError && (
            <p className="text-xs text-destructive">{localError}</p>
          )}
          <div className="flex gap-2">
            <Button variant="outline" size="sm" className="flex-1" onClick={cancelEdit} disabled={saving}>
              <X className="w-3.5 h-3.5 mr-1" /> Cancel
            </Button>
            <Button size="sm" className="flex-1" onClick={save} disabled={saving}>
              <Check className="w-3.5 h-3.5 mr-1" /> {saving ? 'Saving…' : 'Save'}
            </Button>
          </div>
          <p className="text-[11px] text-muted-foreground">
            Names are unique. Changing yours frees the old name for others.
          </p>
        </div>
      )}
    </div>
  );
}
