// Default item blueprints and their required-slot patterns.
// Admins can override any of these via the Craft Patterns editor.

import type { ItemBlueprint } from './types';

export const DEFAULT_BLUEPRINTS: ItemBlueprint[] = [
  // ---------------- BLADED WEAPONS ----------------
  {
    id: 'dagger',
    name: 'Dagger',
    icon: '🗡️',
    slot: 'mainHand',
    category: 'weapon_blade',
    minGrid: 3,
    baseStats: { attack: 4, speed: 2 },
    pattern: [
      { dx: 0, dy: 0, role: 'blade',  acceptTypes: ['metal', 'ore', 'bone'] },
      { dx: 0, dy: 1, role: 'handle', acceptTypes: ['wood', 'bone', 'hide'] },
    ],
  },
  {
    id: 'sword',
    name: 'Sword',
    icon: '⚔️',
    slot: 'mainHand',
    category: 'weapon_blade',
    minGrid: 3,
    baseStats: { attack: 7 },
    pattern: [
      { dx: 0, dy: 0, role: 'blade',  acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 1, role: 'blade',  acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 2, role: 'handle', acceptTypes: ['wood', 'bone', 'hide'] },
    ],
  },
  {
    id: 'axe',
    name: 'Axe',
    icon: '🪓',
    slot: 'mainHand',
    category: 'weapon_blade',
    minGrid: 3,
    baseStats: { attack: 9 },
    pattern: [
      { dx: 0, dy: 0, role: 'blade',  acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 0, role: 'blade',  acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 1, role: 'handle', acceptTypes: ['wood'] },
      { dx: 1, dy: 2, role: 'handle', acceptTypes: ['wood'] },
    ],
  },
  // ---------------- RANGED / MAGIC ----------------
  {
    id: 'bow',
    name: 'Bow',
    icon: '🏹',
    slot: 'mainHand',
    category: 'weapon_ranged',
    minGrid: 3,
    baseStats: { attack: 5, speed: 3 },
    pattern: [
      { dx: 0, dy: 0, role: 'handle', acceptTypes: ['wood'] },
      { dx: 0, dy: 1, role: 'handle', acceptTypes: ['wood'] },
      { dx: 0, dy: 2, role: 'binder', acceptTypes: ['fabric', 'hide'] },
    ],
  },
  {
    id: 'staff',
    name: 'Staff',
    icon: '🪄',
    slot: 'mainHand',
    category: 'weapon_ranged',
    minGrid: 3,
    baseStats: { attack: 3, special: 6 },
    pattern: [
      { dx: 0, dy: 0, role: 'catalyst', acceptTypes: ['gem', 'essence', 'element', 'mote'] },
      { dx: 0, dy: 1, role: 'handle',   acceptTypes: ['wood'] },
      { dx: 0, dy: 2, role: 'handle',   acceptTypes: ['wood'] },
    ],
  },
  // ---------------- OFFHAND ----------------
  {
    id: 'shield',
    name: 'Shield',
    icon: '🛡️',
    slot: 'offHand',
    category: 'armor_heavy',
    minGrid: 3,
    baseStats: { defense: 6 },
    pattern: [
      { dx: 0, dy: 0, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 0, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['wood', 'hide'] },
      { dx: 1, dy: 1, role: 'binder', acceptTypes: ['wood', 'hide'] },
    ],
  },
  // ---------------- ARMOR ----------------
  {
    id: 'helm',
    name: 'Helm',
    icon: '⛑️',
    slot: 'helmet',
    category: 'armor_heavy',
    minGrid: 3,
    baseStats: { defense: 3, maxHp: 5 },
    pattern: [
      { dx: 0, dy: 0, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 0, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['hide', 'fabric'] },
    ],
  },
  {
    id: 'chestplate',
    name: 'Chestplate',
    icon: '🦺',
    slot: 'armor',
    category: 'armor_heavy',
    minGrid: 3,
    baseStats: { defense: 8, maxHp: 10 },
    pattern: [
      { dx: 0, dy: 0, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 0, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 1, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 1, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 2, role: 'binder', acceptTypes: ['hide', 'fabric'] },
    ],
  },
  {
    id: 'leather_tunic',
    name: 'Leather Tunic',
    icon: '🥋',
    slot: 'armor',
    category: 'armor_light',
    minGrid: 3,
    baseStats: { defense: 4, dodge: 3 },
    pattern: [
      { dx: 0, dy: 0, role: 'binder', acceptTypes: ['hide'] },
      { dx: 1, dy: 0, role: 'binder', acceptTypes: ['hide'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['hide', 'fabric'] },
    ],
  },
  {
    id: 'gloves',
    name: 'Gloves',
    icon: '🧤',
    slot: 'gloves',
    category: 'armor_light',
    minGrid: 3,
    baseStats: { defense: 1, dodge: 1 },
    pattern: [
      { dx: 0, dy: 0, role: 'binder', acceptTypes: ['hide', 'fabric'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['hide', 'fabric'] },
    ],
  },
  {
    id: 'boots',
    name: 'Boots',
    icon: '🥾',
    slot: 'boots',
    category: 'armor_light',
    minGrid: 3,
    baseStats: { defense: 2, speed: 2 },
    pattern: [
      { dx: 0, dy: 0, role: 'binder', acceptTypes: ['hide'] },
      { dx: 1, dy: 0, role: 'binder', acceptTypes: ['hide'] },
    ],
  },
  // ---------------- ACCESSORY ----------------
  {
    id: 'ring',
    name: 'Ring',
    icon: '💍',
    slot: 'accessory',
    category: 'accessory',
    minGrid: 3,
    baseStats: { special: 2 },
    pattern: [
      { dx: 0, dy: 0, role: 'guard',    acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 1, role: 'catalyst', acceptTypes: ['gem'] },
    ],
  },
  {
    id: 'amulet',
    name: 'Amulet',
    icon: '📿',
    slot: 'accessory',
    category: 'accessory',
    minGrid: 3,
    baseStats: { special: 3, maxHp: 5 },
    pattern: [
      { dx: 0, dy: 0, role: 'binder',   acceptTypes: ['fabric', 'hide'] },
      { dx: 0, dy: 1, role: 'catalyst', acceptTypes: ['gem', 'essence'] },
    ],
  },
  // ---------------- CONSUMABLE ----------------
  {
    id: 'potion',
    name: 'Potion',
    icon: '🧪',
    slot: 'consumable',
    category: 'consumable',
    minGrid: 3,
    baseStats: {},
    effectId: 'heal_hp',
    pattern: [
      { dx: 0, dy: 0, role: 'base', acceptTypes: ['essence', 'mote'] },
      { dx: 0, dy: 1, role: 'base', acceptTypes: ['herb'] },
    ],
  },
  // ---------------- SCROLL ----------------
  {
    id: 'scroll',
    name: 'Scroll',
    icon: '📜',
    slot: 'scroll',
    category: 'scroll',
    minGrid: 3,
    baseStats: {},
    effectId: 'recipe',
    pattern: [
      { dx: 0, dy: 0, role: 'seal',     acceptTypes: ['fabric', 'hide'] },
      { dx: 0, dy: 1, role: 'catalyst', acceptTypes: ['essence', 'gem', 'rune'] },
    ],
  },
  // ---------------- PORTABLE STATIONS ----------------
  // Craftable inside their parent building. Slot 'consumable' is a legacy
  // reuse so the tool grants a portable-station flag on craft (workshop
  // handler special-cases these blueprint ids).
  {
    id: 'portable_forge',
    name: 'Portable Forge',
    icon: '🔥',
    slot: 'consumable',
    category: 'consumable',
    minGrid: 3,
    baseStats: {},
    effectId: 'grant_portable_forge',
    pattern: [
      { dx: 0, dy: 0, role: 'guard',  acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 0, role: 'guard',  acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['hide'] },
    ],
  },
  {
    id: 'portable_workbench',
    name: 'Portable Workbench',
    icon: '🪚',
    slot: 'consumable',
    category: 'consumable',
    minGrid: 3,
    baseStats: {},
    effectId: 'grant_portable_workbench',
    pattern: [
      { dx: 0, dy: 0, role: 'handle', acceptTypes: ['wood'] },
      { dx: 1, dy: 0, role: 'handle', acceptTypes: ['wood'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['hide', 'fabric'] },
    ],
  },
  {
    id: 'portable_brewing',
    name: 'Portable Brewing Kit',
    icon: '⚗️',
    slot: 'consumable',
    category: 'consumable',
    minGrid: 3,
    baseStats: {},
    effectId: 'grant_portable_brewing',
    pattern: [
      { dx: 0, dy: 0, role: 'base',   acceptTypes: ['herb'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['fabric'] },
    ],
  },
  {
    id: 'portable_enchanting',
    name: 'Portable Enchanting Kit',
    icon: '🔮',
    slot: 'consumable',
    category: 'consumable',
    minGrid: 3,
    baseStats: {},
    effectId: 'grant_portable_enchanting',
    pattern: [
      { dx: 0, dy: 0, role: 'catalyst', acceptTypes: ['essence', 'gem', 'rune'] },
      { dx: 0, dy: 1, role: 'binder',   acceptTypes: ['fabric'] },
    ],
  },
  // ---------------- BUILDING KITS (Town Hall only) ----------------
  // Crafted output is a placeable "Building Kit" — currently surfaces as an
  // inventory item whose crafted stats represent the bonuses the built
  // structure will inherit once world placement is wired up.
  {
    id: 'kit_wall',
    name: 'Wall Kit',
    icon: '🧱',
    slot: 'consumable',
    category: 'building',
    minGrid: 3,
    baseStats: { defense: 20, maxHp: 40 },
    effectId: 'place_building_wall',
    pattern: [
      { dx: 0, dy: 0, role: 'guard',  acceptTypes: ['metal', 'ore', 'soil'] },
      { dx: 1, dy: 0, role: 'guard',  acceptTypes: ['metal', 'ore', 'soil'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['wood', 'hide'] },
    ],
  },
  {
    id: 'kit_watchtower',
    name: 'Watchtower Kit',
    icon: '🗼',
    slot: 'consumable',
    category: 'building',
    minGrid: 3,
    baseStats: { attack: 8, defense: 12, maxHp: 60 },
    effectId: 'place_building_watchtower',
    pattern: [
      { dx: 0, dy: 0, role: 'guard',  acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 1, role: 'handle', acceptTypes: ['wood'] },
      { dx: 0, dy: 2, role: 'handle', acceptTypes: ['wood'] },
    ],
  },
  {
    id: 'kit_farm',
    name: 'Farm Kit',
    icon: '🌾',
    slot: 'consumable',
    category: 'building',
    minGrid: 3,
    baseStats: { stamina: 10, maxHp: 30 },
    effectId: 'place_building_farm',
    pattern: [
      { dx: 0, dy: 0, role: 'base',   acceptTypes: ['soil', 'seed'] },
      { dx: 1, dy: 0, role: 'base',   acceptTypes: ['soil', 'seed'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['wood'] },
    ],
  },
  {
    id: 'kit_storehouse',
    name: 'Storehouse Kit',
    icon: '🏚️',
    slot: 'consumable',
    category: 'building',
    minGrid: 3,
    baseStats: { defense: 8, maxHp: 50 },
    effectId: 'place_building_storehouse',
    pattern: [
      { dx: 0, dy: 0, role: 'binder', acceptTypes: ['wood'] },
      { dx: 1, dy: 0, role: 'binder', acceptTypes: ['wood'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['wood'] },
      { dx: 1, dy: 1, role: 'guard',  acceptTypes: ['metal', 'ore'] },
    ],
  },
  // ---------------- LARGE-STATION EXCLUSIVES (4×4 workbench+) ----------------
  {
    id: 'greatsword',
    name: 'Greatsword',
    icon: '⚔️',
    slot: 'mainHand',
    category: 'weapon_blade',
    minGrid: 4,
    baseStats: { attack: 14, speed: -1 },
    pattern: [
      { dx: 0, dy: 0, role: 'blade',  acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 1, role: 'blade',  acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 2, role: 'blade',  acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 3, role: 'handle', acceptTypes: ['wood', 'bone'] },
    ],
  },
  {
    id: 'warhammer',
    name: 'Warhammer',
    icon: '🔨',
    slot: 'mainHand',
    category: 'weapon_blade',
    minGrid: 4,
    baseStats: { attack: 12, defense: 2 },
    pattern: [
      { dx: 0, dy: 0, role: 'guard',  acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 0, role: 'guard',  acceptTypes: ['metal', 'ore'] },
      { dx: 2, dy: 0, role: 'guard',  acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 1, role: 'handle', acceptTypes: ['wood'] },
      { dx: 1, dy: 2, role: 'handle', acceptTypes: ['wood'] },
      { dx: 1, dy: 3, role: 'handle', acceptTypes: ['wood', 'hide'] },
    ],
  },
  {
    id: 'full_plate',
    name: 'Full Plate',
    icon: '🛡️',
    slot: 'armor',
    category: 'armor_heavy',
    minGrid: 4,
    baseStats: { defense: 16, maxHp: 22, speed: -2 },
    pattern: [
      { dx: 0, dy: 0, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 0, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 2, dy: 0, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 1, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 1, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 2, dy: 1, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 0, dy: 2, role: 'guard', acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 2, role: 'binder', acceptTypes: ['fabric', 'hide'] },
      { dx: 2, dy: 2, role: 'guard', acceptTypes: ['metal', 'ore'] },
    ],
  },
  {
    id: 'hooded_cloak',
    name: 'Hooded Cloak',
    icon: '🧥',
    slot: 'back',
    category: 'armor_light',
    minGrid: 4,
    baseStats: { defense: 4, dodge: 4, special: 2 },
    pattern: [
      { dx: 0, dy: 0, role: 'binder', acceptTypes: ['fabric'] },
      { dx: 1, dy: 0, role: 'binder', acceptTypes: ['fabric'] },
      { dx: 2, dy: 0, role: 'binder', acceptTypes: ['fabric'] },
      { dx: 0, dy: 1, role: 'binder', acceptTypes: ['fabric', 'hide'] },
      { dx: 1, dy: 1, role: 'catalyst', acceptTypes: ['essence', 'rune', 'mote'] },
      { dx: 2, dy: 1, role: 'binder', acceptTypes: ['fabric', 'hide'] },
    ],
  },
  // ---------------- MASTER-STATION EXCLUSIVES (5×5 enchanting) ----------------
  {
    id: 'runed_greatstaff',
    name: 'Runed Greatstaff',
    icon: '🪄',
    slot: 'mainHand',
    category: 'weapon_ranged',
    minGrid: 5,
    baseStats: { attack: 6, special: 14, maxHp: 8 },
    pattern: [
      { dx: 1, dy: 0, role: 'catalyst', acceptTypes: ['gem', 'essence', 'rune'] },
      { dx: 0, dy: 1, role: 'catalyst', acceptTypes: ['essence', 'element', 'mote'] },
      { dx: 1, dy: 1, role: 'handle',   acceptTypes: ['wood'] },
      { dx: 2, dy: 1, role: 'catalyst', acceptTypes: ['essence', 'element', 'mote'] },
      { dx: 1, dy: 2, role: 'handle',   acceptTypes: ['wood'] },
      { dx: 1, dy: 3, role: 'handle',   acceptTypes: ['wood'] },
      { dx: 1, dy: 4, role: 'binder',   acceptTypes: ['fabric', 'hide'] },
    ],
  },
  {
    id: 'crown_of_authority',
    name: 'Crown of Authority',
    icon: '👑',
    slot: 'helmet',
    category: 'accessory',
    minGrid: 5,
    baseStats: { defense: 6, maxHp: 20, special: 10 },
    pattern: [
      { dx: 0, dy: 0, role: 'guard',    acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 0, role: 'catalyst', acceptTypes: ['gem'] },
      { dx: 2, dy: 0, role: 'guard',    acceptTypes: ['metal', 'ore'] },
      { dx: 3, dy: 0, role: 'catalyst', acceptTypes: ['gem'] },
      { dx: 4, dy: 0, role: 'guard',    acceptTypes: ['metal', 'ore'] },
      { dx: 1, dy: 1, role: 'guard',    acceptTypes: ['metal', 'ore'] },
      { dx: 2, dy: 1, role: 'catalyst', acceptTypes: ['essence', 'rune'] },
      { dx: 3, dy: 1, role: 'guard',    acceptTypes: ['metal', 'ore'] },
    ],
  },
];

/** Blueprint ids that grant a portable-station tool flag when crafted. */
export const PORTABLE_STATION_BLUEPRINTS: Record<string, 'forge' | 'workbench' | 'brewing' | 'enchanting'> = {
  portable_forge: 'forge',
  portable_workbench: 'workbench',
  portable_brewing: 'brewing',
  portable_enchanting: 'enchanting',
};

export function getBlueprint(id: string): ItemBlueprint | undefined {
  return DEFAULT_BLUEPRINTS.find((b) => b.id === id);
}
