// Hook + helpers for the public username system used by leaderboards.
//
// - `useMyUsername()` returns the signed-in user's current username (or null).
//   Players without a name are auto-assigned one (Trainer_xxxxx) so they
//   show up on leaderboards immediately. `autoGenerated` tells callers
//   whether the name was system-picked.
// - `setMyUsername(name)` validates client-side and calls the secure RPC.
//   Returns `wasFirstManual` so the UI can grant a one-time reward when the
//   player customises the auto-generated name.
// - `submitTowerFloor(towerId, floor, …)` posts a best-floor; it's a no-op for
//   signed-out users and silently skipped if no username has been set yet.

import { useCallback, useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from './useAuth';

export const USERNAME_REGEX = /^[A-Za-z0-9_-]{3,20}$/;

export function validateUsername(name: string): string | null {
  const trimmed = name.trim();
  if (trimmed.length === 0) return 'Username cannot be empty';
  if (!USERNAME_REGEX.test(trimmed)) {
    return 'Use 3–20 characters: letters, numbers, _ or -';
  }
  return null;
}

export function useMyUsername() {
  const { user, isAuthenticated, loading: authLoading } = useAuth();
  const [username, setUsername] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState<boolean>(false);
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    if (!isAuthenticated || !user) {
      setUsername(null);
      setAutoGenerated(false);
      setLoading(false);
      return;
    }
    setLoading(true);
    const { data, error } = await supabase.rpc('get_my_username_info');
    let info = (data as { username?: string | null; auto_generated?: boolean } | null) ?? null;
    if (error) {
      console.error('get_my_username_info failed', error);
    }
    // No name yet -> server picks one so the player can appear on boards.
    if (!info?.username) {
      const { data: ensured, error: ensureErr } = await supabase.rpc('ensure_username');
      if (ensureErr) {
        console.warn('ensure_username failed', ensureErr);
      } else {
        const e = ensured as { username?: string; auto_generated?: boolean } | null;
        if (e?.username) info = { username: e.username, auto_generated: e.auto_generated ?? true };
      }
    }
    setUsername(info?.username ?? null);
    setAutoGenerated(Boolean(info?.auto_generated));
    setLoading(false);
  }, [isAuthenticated, user]);

  useEffect(() => {
    if (authLoading) return;
    refresh();
  }, [authLoading, refresh]);

  return { username, autoGenerated, loading: authLoading || loading, refresh, isAuthenticated };
}

export async function setMyUsername(name: string): Promise<
  | { ok: true; username: string; wasFirstManual: boolean }
  | { ok: false; error: string }
> {
  const localError = validateUsername(name);
  if (localError) return { ok: false, error: localError };
  const { data, error } = await supabase.rpc('set_username', { _username: name.trim() });
  if (error) return { ok: false, error: error.message };
  const result = data as { username?: string; was_first_manual?: boolean } | null;
  return {
    ok: true,
    username: result?.username ?? name.trim(),
    wasFirstManual: Boolean(result?.was_first_manual),
  };
}

export async function submitDiscoveryCount(count: number, worldSeed?: number | null): Promise<void> {
  if (!Number.isFinite(count) || count < 0) return;
  try {
    await supabase.rpc('submit_discovery_count', {
      _count: Math.floor(count),
      _world_seed: worldSeed != null && Number.isFinite(worldSeed) ? Math.floor(worldSeed) : null,
    });
  } catch (e) {
    console.warn('submit_discovery_count failed', e);
  }
}

export async function submitExplorationCount(count: number, worldSeed?: number | null): Promise<void> {
  if (!Number.isFinite(count) || count < 0) return;
  try {
    await supabase.rpc('submit_exploration_count', {
      _count: Math.floor(count),
      _world_seed: worldSeed != null && Number.isFinite(worldSeed) ? Math.floor(worldSeed) : null,
    });
  } catch (e) {
    console.warn('submit_exploration_count failed', e);
  }
}

export async function submitTowerFloor(
  towerId: string,
  floor: number,
  partySnapshot?: unknown,
  runSeconds?: number,
): Promise<void> {
  if (!towerId || !Number.isFinite(floor) || floor < 1) return;
  try {
    await supabase.rpc('submit_tower_floor', {
      _tower_id: towerId,
      _floor: Math.floor(floor),
      _party_snapshot: (partySnapshot ?? null) as never,
      _run_seconds: runSeconds ?? null,
    });
  } catch (e) {
    // Leaderboard submission is best-effort; never block gameplay.
    console.warn('submit_tower_floor failed', e);
  }
}
