      - name: Force Vite Build (Relative Paths for itch.io)
        run: |
          export VITE_SUPABASE_URL="https://ijhisspxewnmriuewaxs.supabase.co"
          export VITE_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqaGlzc3B4ZXdubXJpdWV3YXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzODE3MDMsImV4cCI6MjA4NDk1NzcwM30.X9LQKEOkhckY5d3P7HWvxvvqHKctQU9CuegZgW85_zI"
          export CI=false
          npx vite build --outDir actual_dist --base ./
